### ISSUE TITLE
Add more content

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/engineering-management#4]
Add further relevant content in the people leadership space.

* anything that might coaching, leadership, management tools and activities
* anything that might help in the productivity, communications, task management space.

the detail is light, because it will probably be things I've not seen or heard of before.

**Comment by Angelfirenze01** [comment]
This is not a good 'this-is-the-first-thing-I've-ever-tried-to-fix' issue.  Add what specific kind of content, as far as whether you're describing tools to help all employee types or just those who work in offices?  What sort of resources do you allow?  If I wanted to direct you to The Fabulous (a behavioral modification application for mobile devices) and describe their mission and how your information might benefit from expanding using some of their resources and habit-changing behaviors, how would I do so?

**Comment by MatBenfield** [comment]
hi @Angelfirenze01 , you are right and I'm sorry about that. I wanted to ensure I had an issue raised so it can be found.

I'll update it to reflect some of things I would be looking for - although the detail is unknown to me. Thanks for taking the time to point this out.

best wishes

**Comment by Angelfirenze01** [comment]
Best wishes to you, too!
